### ISSUE TITLE
Unicode error on resources link

### ISSUE THREAD

**Issue by avaneeshd** [diging/jars#13]
Resources link throws unicode error after importing a collection that throws unicode error. This is similar to other unicode issue #6 , but since resources link is broken I cannot try importing any new collections.
<img width="1183" alt="screen shot 2015-09-17 at 4 05 35 pm" src="https://cloud.githubusercontent.com/assets/8482721/9997752/baddd710-6042-11e5-9c62-121919f93810.png">

Steps:
1. Build a collection using Zotero by collecting records from jstor.org and export the collection with files.
2. Login as admin into Jars application.
3. Click on Resources Link.
4. Select Add Resources > Bulk.
5. Zip and upload the collection into Jars. Jars throws Unicode error while uploading (Issue reported by @nakapika ).
6. Go Back using browser back button and click on resources link  again.
7. http://127.0.0.1:8000/admin/cookies/resource/ page also gives unicode error.

**Comment by erickpeirson** [comment]
What are other issues that report this problem? (Hint: you can reference other issues using the hash (#) + issue number)

I assume that you'll reset your development database, so that you can keep working? ;-)

**Comment by erickpeirson** [comment]
@avaneeshd Did you take a look at [the line that is throwing the exception](https://github.com/diging/jars/blob/master/jars/cookies/forms.py#L28)? You might be able to fix this particular problem quite easily...
