### ISSUE TITLE
Links to home and admin pages

### ISSUE THREAD

**Issue by NicoletteFurtado** [diging/jars#15]
When the user logs in, and the sees the first page with the Jars logo, there is a link to the Admin page which is called 'Home'. Once this link is clicked, it leads to the admin page which again has a link to the Home page called home. 
Bug: The link on the home page should be named Admin, instead of Home.

**Comment by erickpeirson** [comment]
@NicoletteFurtado Good catch! Go ahead and assign yourself (see right) to the issue, create your branch, and go for it. :-)
