### ISSUE TITLE
UnicodeEncodeError when using bulk upload

### ISSUE THREAD

**Issue by nakapika** [diging/jars#6]
![screenshot from 2015-09-16 11 08 32](https://cloud.githubusercontent.com/assets/8505419/9913766/5bc88654-5c63-11e5-879c-bf3a608118b6.png)

**Comment by nakapika** [comment]
Similar issue reference: https://github.com/diging/tethne/issues/85

**Comment by erickpeirson** [comment]
Can you add some details about how to recreate this error? See [this guide](http://diging.github.io/course-book/2015/08/19/github-issues.html) for reference

**Comment by nakapika** [comment]
1.  Collect some bibliographic records using Zotero
2. Arrange them into collections based on the subject of the records
3. Export the collection along with the data files
4. Zip the data up and from the JARS Django admin interface, try adding your Zotero collections (Add Resource > Bulk)

Expected: Successful bulk import with option to save collections
Actual: Throwing UnicodeEncodeError as seen in attached screenshot

Last Commit SHA: a2b28a313650807d28212545661b6e7a387d6bea

**Comment by erickpeirson** [comment]
Cool. So this happens when you click the "Submit" button on the bulk upload form?

**Comment by nakapika** [comment]
Yes! The particular collection I created is always throwing this error. Should I discuss this with Nischal as he is working on a similar unicode encoding error?

**Comment by erickpeirson** [comment]
Yes, work together on this. Thanks!

**Comment by nischalsamji** [comment]
@nakapika For starters, you can look at this !!! http://www.joelonsoftware.com/articles/Unicode.html

**Comment by erickpeirson** [comment]
Great article!

---
Erick Peirson
Postdoctoral Scholar
ASU-SFI Center for Biosocial Complexity
Arizona State University

**Comment by nakapika** [comment]
Really good article! So does this mean that we should use UTF-8 in all our projects to prevent encoding errors?

**Comment by nakapika** [comment]
@nischalsamji and I have been working on this for a while now. The problem is that the conference paper names have an apostrophe which is not encoded in utf-8 and hence it is breaking the code. We tried encoding all the text to utf-8 but it didn't work. We will continue to work on this today to find a permanent solution.

**Comment by erickpeirson** [comment]
@nakapika @nischalsamji Thanks for tackling this. Don't the .rdf files have UTF-8 encoding when they are created?

**Comment by nischalsamji** [comment]
@erickpeirson When the file contents has a unicode character, the parser works fine. If there is a unicode character in the file name, it is throwing an error.
