### ISSUE TITLE
._ mac files while adding resources

### ISSUE THREAD

**Issue by shivamprakash** [diging/jars#7]
On adding a zip file, a ._ file is also uploaded for all all files in the zipped folder.
![screen shot 2015-09-14 at 12 00 22 pm](https://cloud.githubusercontent.com/assets/1397157/9858957/887a2e1e-5ad8-11e5-9dcc-4c7833606a6c.png)

**Comment by erickpeirson** [comment]
Hey @shivamprakash, be sure to add a label, a milestone (v0.8), and assign yourself!

**Comment by erickpeirson** [comment]
@shivamprakash Be sure to add a label, a milestone (v0.8), and assign youreself!
