### ISSUE TITLE
Uploading RDF file instead of zipped RDF along with files throws exception

### ISSUE THREAD

**Issue by PramodhN** [diging/jars#9]
Steps
--------
1. Login as admin.
2. Click on add collection.
3. Choose add resources.
4. Select 'bulk' option from dropdown and submit.
5. Choose an RDF file and click on submit.
6. An exception is thrown - BadZipfile at /admin/cookies/resource/bulk/

Expected result
---------------------
Should ask the user to choose a proper zip file and redirect back to the original form.

**Comment by erickpeirson** [comment]
@PramodhN Any updates on this?

**Comment by PramodhN** [comment]
This is fixed - Pull request #10
